### PR TITLE
fix: add myself to authors

### PR DESCRIPTION
**Pull request by 15696**
fix

### CODE REVIEW

**Comment by 15696** [comment]
LGTM

**Comment by vcokltfre** [comment]
Bruh you can't 'LGTM' your own PR lmao

**Comment by vcokltfre** [comment]
Also your first commit is literally adding yourself to authors so like, no?

**Comment by 15696** [comment]
*uncloses*

**Comment by 15696** [comment]
LGTM can we merge

**Comment by ToxicKidz** [comment]
LBTM

**Pull request closed without merging**
