### PR TITLE
fix: add myself to authors

### PR DESCRIPTION
**Pull request by 15696**
Idk why last one no worky

### CODE REVIEW

**Comment by 15696** [comment]
LGTM

**Comment by 15696** [comment]
Thanks

**Comment by asleep-cult** [comment]
How do you ban someone from making pull requests?

**Comment by 15696** [comment]
Press the merge button

**Comment by 15696** [comment]
That's how

**Comment by 15696** [comment]
I agree

**Comment by 15696** [comment]
@vcokltfre @ChiliPy @anand2312 hi

**Pull request closed without merging**
